config_version = 15

[bar]
order = [ "default" ]

    [bar.default]
    border = "primary"
    capsule_padding = 5.0
    center = [ "date", "bar", "clock" ]
    contact_shadow = true
    end = [ "group:g1", "notifications", "clipboard", "volume", "bluetooth", "network", "battery", "session" ]
    font_weight = 400
    margin_ends = 0
    padding = 0
    position = "left"
    radius_bottom_left = 0
    radius_top_left = 0
    start = [ "control-center", "bar_2", "group:g2", "workspaces", "media", "audio_visualizer" ]
    thickness = 30

        [bar.default.dead_zone.actions]
        back = "bar-show"

        [[bar.default.capsule_group]]
        accordion = false
        accordion_direction = "end"
        border = "primary"
        border_width = 0.0
        enabled = false
        fill = "surface_variant"
        id = "g2"
        members = [ "wallpaper", "wallhaven", "mpvpaper" ]
        opacity = 1.0
        padding = 0.0

        [[bar.default.capsule_group]]
        accordion = false
        accordion_direction = "end"
        border = ""
        border_width = 1.0
        enabled = true
        fill = "surface_variant"
        id = "g1"
        members = [ "cpu", "ram", "network_tx", "network_rx" ]
        opacity = 1.0
        padding = 5.0

[battery]
warning_threshold = 25

[[control_center.shortcuts]]
type = "wifi"

[[control_center.shortcuts]]
type = "bluetooth"

[[control_center.shortcuts]]
type = "notification"

[[control_center.shortcuts]]
type = "clipboard"

[[control_center.shortcuts]]
type = "icefish/phone-connect:tile"

[[control_center.shortcuts]]
type = "noctalia/wallhaven:shortcut"

[desktop_widgets]
schema_version = 2
widget_order = []

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [desktop_widgets.widget]

[dock]
background_opacity = 0.74999998323619366
border = "primary"
cross_axis_padding = 0
enabled = true
icon_size = 25
item_spacing = 4
launcher_icon = "math-function"
launcher_position = "start"
magnification = false
position = "right"
reserve_space = false

[hot_corners]
enabled = true

    [hot_corners.top_right]
    action = "window_switcher"

[idle]
behavior_order = [ "screen-off", "lock", "lock-and-suspend" ]
enabled = true

    [idle.behavior.lock]
    action = "lock"
    enabled = false
    timeout = 600.0

    [idle.behavior.lock-and-suspend]
    action = "lock_and_suspend"
    enabled = false
    timeout = 900.0

    [idle.behavior.screen-off]
    action = "screen_off"
    enabled = false
    timeout = 300.0

[location]
auto_locate = true

[lockscreen]
blur_intensity = 0.099999997764825821
tint_intensity = 0.4999999888241291

[lockscreen_widgets]
enabled = true
schema_version = 2
widget_order = [ "lockscreen-login-box@eDP-1", "lockscreen-widget-0000000000000001", "lockscreen-widget-0000000000000002" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 196.0
    box_width = 720.0
    cx = 800.0
    cy = 818.0
    output = "eDP-1"
    placement_height = 1000.0
    placement_width = 1600.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000001]
    box_height = 320.0
    box_width = 688.0
    cx = 800.0
    cy = 372.0
    output = "eDP-1"
    placement_height = 1000.0
    placement_width = 1600.0
    rotation = 0.0
    type = "clock"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000001.settings]
        background = false
        background_color = "on_tertiary"
        clock_style = "digital"
        format = "{:%H:%M:%S}"

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000002]
    box_height = 112.0
    box_width = 496.0
    cx = 800.0
    cy = 572.0
    output = "eDP-1"
    placement_height = 1000.0
    placement_width = 1600.0
    rotation = 0.0
    type = "audio_visualizer"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000002.settings]
        background = false
        bands = 32
        color_1 = "tertiary"
        show_when_idle = true

[osd]
background_opacity = 0.4999999888241291

    [osd.kinds]
    media = false

[plugin_settings."icefish/phone-connect"]
battery_display = "hidden"
enable_charging_animation = false
panel_placement = "widget"

[plugin_settings."noctalia/mpvpaper"]
picker_open_near_click = true
picker_placement = "floating"

[plugin_settings."noctalia/screen_recorder"]
video_encoder = "cpu"

[plugin_settings."noctalia/timer"]
panel_placement = "floating"

[plugin_settings."noctalia/wallhaven"]
browser_open_near_click = true
browser_placement = "floating"
download_dir = "/home/econhead/Pictures/wallpapers/aenami"

[plugin_settings."riversyx/noctaproton-vpn"]
panel_placement = "floating"

[plugin_settings."yngwe/wallpaperCarousel"]
wallpaperDirectory = "/home/econhead/Pictures/wallpapers/aenami"

[plugins]
enabled = [
    "icefish/phone-connect",
    "yngwe/wallpaperCarousel",
    "noctalia/bitwarden",
    "noctalia/timer",
    "noctalia/wallhaven",
    "noctalia/screen_recorder",
    "noctalia/mpvpaper"
]

[shell]
font_family = "ComicShannsMono Nerd Font"
panel_anchor_bar = "default"
screen_time_enabled = true

    [shell.launcher]
    categories = false
    show_app_origin_indicator = false

        [shell.launcher.providers.emoji]
        global = false

    [shell.panel]
    clipboard_position = "auto"
    control_center_placement = "floating"
    open_near_click_clipboard = true
    open_near_click_control_center = true
    open_near_click_wallpaper = true
    session_placement = "floating"
    session_position = "center"
    transparency_mode = "glass"
    wallpaper_placement = "floating"

    [shell.screen_corners]
    size = 16

    [shell.screenshot]
    confirm_region = true
    directory = "/home/econhead/Pictures/Screenshots"

    [shell.session]
    grid_columns = 5

    [shell.window_switcher]
    mru = true

[theme]
builtin = "Ayu"
community_palette = "Gruvbox Material Hard"
mode = "dark"
source = "wallpaper"
wallpaper_scheme = "m3-tonal-spot"

    [theme.templates]
    builtin_ids = [ "btop", "gtk3", "gtk4", "hyprland", "kcolorscheme", "kitty", "qt" ]
    community_ids = [ "qutebrowser", "discord" ]

[wallpaper]
directory = "/home/econhead/Pictures/wallpapers"

    [wallpaper.default]
    path = "/home/econhead/Pictures/wallpapers/aenami/wallhaven-zpvvkg_2560x1600.png"

    [wallpaper.last]
    path = "/home/econhead/Pictures/wallpapers/aenami/wallhaven-zpvvkg_2560x1600.png"

    [wallpaper.monitors.eDP-1]
    path = "/home/econhead/Pictures/wallpapers/aenami/wallhaven-zpvvkg_2560x1600.png"

[widget.bar]
capsule = true
capsule_border = "primary"
show_idle_on_horizontal = false
type = "noctalia/timer:bar"

[widget.bar_2]
enabled = false
scale = 1.1500000000000001
type = "icefish/phone-connect:bar"

[widget.clock]
format = "{:%I:%M:%p}"

[widget.control-center]
capsule = true
capsule_border_width = 0.5
capsule_padding = 1
glyph = "function"
icon_color = "secondary"
scale = 1.4500000000000002

[widget.cpu]
capsule_padding = 10

[widget.launcher]
enabled = false

[widget.media]
art_size = 25
capsule = true
hide_when_no_media = true
rotate_album_art = true
scale = 0.85000000000000009
show_progress = true
title_scroll = "always"

[widget.mpvpaper]
type = "noctalia/mpvpaper:mpvpaper"

[widget.network]
font_scale = 0.90000000000000002
show_label = false
vpn_status = "hidden"

[widget.network_rx]
capsule_padding = 10
enabled = false
network_speed_compact = true
visualization = "none"

[widget.network_tx]
capsule_padding = 10
enabled = false
network_speed_compact = true
visualization = "none"

[widget.ram]
font_scale = 0.90000000000000002
stat = "ram_pct"

[widget.session]
capsule = true
capsule_border = "primary"
capsule_radius = "auto"
icon_color = "error"
scale = 0.85000000000000009

[widget.tray]
enabled = false

[widget.volume]
show_label = false

[widget.wallhaven]
enabled = false
type = "noctalia/wallhaven:wallhaven"

[widget.workspaces]
active_pill_size = 1.5
capsule_border = "primary"
capsule_border_width = 0.0
hide_when_empty = true
max_label_chars = 2