#!/bin/bash

source "$CONFIG_DIR/colors.sh"
PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"

##### Bar Appearance #####

sketchybar --bar position=top \
                 height=28 \
                 blur_radius=0 \
                 #color=$BAR_COLOR       

sketchybar --bar "${bar[@]}"

##### Changing Defaults #####

default=(
  padding_left=3
  padding_right=3
  icon.font="Hack Nerd Font:Regular:15.0"
  label.font="SF Pro:Semibold:15.0"
  icon.color=$WHITE
  label.color=$WHITE
  icon.padding_left=10
  icon.padding_right=0
  label.padding_left=10
  label.padding_right=10
  background.color=$ITEM_BG_COLOR
  background.corner_radius=5
  background.height=24
)
sketchybar --default "${default[@]}"

##### Left Items #####

source $ITEM_DIR/apple.sh
source $ITEM_DIR/aerospace_window_title.sh
source $ITEM_DIR/music.sh


##### Right Items #####

source $ITEM_DIR/calendar.sh
source $ITEM_DIR/volume.sh
source $ITEM_DIR/battery.sh
source $ITEM_DIR/cpu_usage.sh

  
##### Force all scripts to run the first time #####
sketchybar --update

sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$(aerospace list-workspaces --focused)
