-- Generated by HyprMod

-- Settings
hl.config({
    general = {
        col = {
            active_border = {
                colors = {"rgba(ffffffff)", "rgba(986a44ff)"},
                angle = 45,
            },
            inactive_border = {
                colors = {"rgba(5e5c64ff)"},
                angle = 45,
            },
        },
        resize_on_border = true,
    },
})
