theme {
    color_scheme = /home/econhead/.local/share/color-schemes/noctalia.colors
    style = Breeze 

    font = Sans Serif
    font_size = 9

    font_fixed = monospace
    font_fixed_size = 9
}
