-- Generated by HyprMod

-- Environment
hl.env("XCURSOR_THEME", "Adwaita")
hl.env("XCURSOR_SIZE", "24")

-- Settings
hl.config({
    general = {
        border_size = 2,
        col = {
            active_border = "0xfffbba73",
            inactive_border = "0xff19120c",
        },
        resize_on_border = true,
    },
})
