color0 #51453a
color1 #ffb4ab
color2 #fcb975
color3 #e1c1a4
color4 #c0cc9a
color5 #fcb975
color6 #e1c1a4
color7 #efe0d5
color8 #9d8e81
color9 #ffb4ab
color10 #fcb975
color11 #e1c1a4
color12 #c0cc9a
color13 #fcb975
color14 #e1c1a4
color15 #efe0d5

cursor                #efe0d5
cursor_text_color     #19120c
background            #19120c
foreground            #efe0d5
selection_foreground  #d5c3b5
selection_background  #51453a
active_border_color   #fcb975
inactive_border_color #51453a
url_color             #fcb975

active_tab_foreground   #4a2800
active_tab_background   #fcb975
inactive_tab_foreground #d5c3b5
inactive_tab_background #51453a
cursor_trail_color      #d5c3b5
