color0 #4d4639
color1 #ffb4ab
color2 #e8c26c
color3 #d7c4a0
color4 #b0cfaa
color5 #e8c26c
color6 #d7c4a0
color7 #ebe1d4
color8 #999080
color9 #ffb4ab
color10 #e8c26c
color11 #d7c4a0
color12 #b0cfaa
color13 #e8c26c
color14 #d7c4a0
color15 #ebe1d4

cursor                #ebe1d4
cursor_text_color     #17130b
background            #17130b
foreground            #ebe1d4
selection_foreground  #d0c5b4
selection_background  #4d4639
active_border_color   #e8c26c
inactive_border_color #4d4639
url_color             #e8c26c

active_tab_foreground   #3f2e00
active_tab_background   #e8c26c
inactive_tab_foreground #d0c5b4
inactive_tab_background #4d4639
cursor_trail_color      #d0c5b4
