color0 #51443b
color1 #ffb4ab
color2 #ffb77b
color3 #e3c0a5
color4 #c4cb97
color5 #ffb77b
color6 #e3c0a5
color7 #efe0d6
color8 #9e8e82
color9 #ffb4ab
color10 #ffb77b
color11 #e3c0a5
color12 #c4cb97
color13 #ffb77b
color14 #e3c0a5
color15 #efe0d6

cursor                #efe0d6
cursor_text_color     #19120c
background            #19120c
foreground            #efe0d6
selection_foreground  #d6c3b6
selection_background  #51443b
active_border_color   #ffb77b
inactive_border_color #51443b
url_color             #ffb77b

active_tab_foreground   #4c2700
active_tab_background   #ffb77b
inactive_tab_foreground #d6c3b6
inactive_tab_background #51443b
cursor_trail_color      #d6c3b6
