set-option -sa terminal-overrides ",xterm*:Tc"
# set -g mouse on

set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

unbind C-b
set -g prefix C-Space
bind C-Space send-prefix
# set -g status-position top

# set -g @catppuccin_flavour 'Mocha'

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
# set -g @plugin 'dreamsofcode-io/catppuccin-tmux'
set -g @plugin 'catppuccin/tmux#v0.3.0'

source-file ~/.config/tmux/theme.conf
run '~/.tmux/plugins/tpm/tpm'
