modmap:
  - name: CapsLock -> Ctrl when held, Esc when tapped
    remap:
      KEY_CAPSLOCK:
        held: KEY_LEFTCTRL
        alone: KEY_ESC
        alone_timeout_millis: 200

  - name: Right Command -> Right Click
    remap:
      KEY_RIGHTMETA:
        skip_key_event: true
        press:
          - { press: BTN_RIGHT }
        release:
          - { release: BTN_RIGHT }

  - name: Right Control -> Right Click
    remap:
      KEY_RIGHTCTRL:
        skip_key_event: true
        press:
          - { press: BTN_RIGHT }
        release:
          - { release: BTN_RIGHT }
